### ISSUE TITLE
More hook options

### ISSUE THREAD

**Issue by mvdan** [LemonBoy/ldm#31]
I propose that we add more options like `-c path/to/script`. For example, an option `-e "STRING"` that would let you execute shell commands as in `bash -c "STRING"`. This would be helpful if you just want to run simple commands like a notify event, for which a script is perhaps too overkill and a bit redundant.

It would also be nice to be able to tell the hook script or commands what actually happened, for example with shell variables. For instance:
- LDM_MOUNT=1 if a mount happened, 0 if an unmount happened
- LDM_DEVICE=/dev/... for the device mounted/unmounted
- LDM_MOUNTPOINT=/path/... for the path that it was mounted to or umounted from

So that then, you could use these in the script and reliably know what did ldm do to call you. It is also much safer and easier than having to parse /etc/mtab, which might have unexpected results if multiple events happen simoultaneously.

I can do a pull request with these if you want, but I wanted to propose the ideas first.

**Comment by Link-Satonaka** [comment]
I'm having trouble simply passing an argument to a script.

`-c handler.sh` works, but `-c handler.sh ldm` does not: `The callback script isn't executable!`

I've tried many different' quoting variations and using sh -c and so on, but I cannot figure it out.

**Comment by LemonBoy** [comment]
The `-c` parameters expects a path to an executable script, hence the error.
