### ISSUE TITLE
umask

### ISSUE THREAD

**Issue by steelsquid** [LemonBoy/ldm#32]
Hello! 
Would be great if it the umask could be configured.

Sincerely
Andreas Nilsson

**Comment by pejobo** [comment]
Any progress on this?

**Comment by LemonBoy** [comment]
Please check out the mask branch :)

**Comment by pejobo** [comment]
Did this ;) Works for me, thank you! This was the final bit needed for my raspberry pi "server"..

**Comment by pejobo** [comment]
One thing, it mounted my boot partition:
/dev/mmcblk0p2 on / type ext4 (rw,relatime,data=ordered)
[..]
/dev/mmcblk0p2 on /media/0d6d30bb-1671-4656-9f6e-a49e309f81af type ext4 (rw,relatime,data=ordered)

Didn't mentioned this before. I haven't done a reboot after updating the binaries.

**Comment by LemonBoy** [comment]
I'll merge the branch into the master if you say it does work fine, I've only tested the part that does the parsing of the mask.
The other issue deserves a separate ticket :)

**Comment by pejobo** [comment]
I tested umask, both in numerical and textual form without issue. Didn't tested the seperate file and folder mask yet.

**Comment by LemonBoy** [comment]
With some good faith I think this can be closed then :D

**Comment by pejobo** [comment]
Is there a plan to merge this to master? I accidentally updated my installation on arch and until I noticed it that "mask" is no longer working I lost some tv recordings..

**Comment by LemonBoy** [comment]
Sorry to hear that but it's been merged nearly two months ago...

**Comment by pejobo** [comment]
Ok, my fault, didn't check that. https://aur.archlinux.org/packages/ldm/ says "Last Updated: 	2015-05-05 21:56". This doesn't seem to include the "-m" switch.

**Comment by pejobo** [comment]
My fault, it's included. Perhaps I had some old binaries laying around. Sorry for the confusion.
