### ISSUE TITLE
Include 'armv7h' in PKGBUILD arch list

### ISSUE THREAD

**Issue by pejobo** [LemonBoy/ldm#40]
Tried it on my raspberry pi 2, works like a charm!
Thx for your good work!!

**Comment by pejobo** [comment]
Sorry, this is clearly no issue here :)

**Comment by LemonBoy** [comment]
I'm the PKGBUILD mantainer too :) let's keep this open as a reminder

**Comment by LemonBoy** [comment]
@pejobo I see you've added something to the systemd service, mind sending a PR ? :)

**Comment by pejobo** [comment]
@LemonBoy You mean the comment here: https://aur.archlinux.org/packages/ldm/
This is a call to a shell script before service start which removes "orphaned" mount points. This should circumvent the creation of additional mount points with a trailing underscore in the name after a server crash or power outage.
I'm not sure this is of interest for others. But when you think it's a good idea..

**Comment by pejobo** [comment]
Btw. in my opinion ldm should be mentioned in the arch wiki. I tried some other solutions which all doesn't suited my need or were to bloated in my mind. And it was just coincidence I found a blog post about ldm (https://aur.archlinux.org/packages/ldm/).

**Comment by LemonBoy** [comment]
@pejobo v0.6 is released and the new PKGBUILDS have been uploaded :D

**Comment by pejobo** [comment]
Thank you, works like a charm :)

**Comment by benoliver999** [comment]
armv6h also works btw
