### ISSUE TITLE
Boot partition is mounted to specified mount dir

### ISSUE THREAD

**Issue by pejobo** [LemonBoy/ldm#44]
Tested on Raspberry Pi 2 with arch linux. On Pi the boot partition is typically /dev/mmcblk0p2.

This is an extract of the mount output (I'm mounting to /media):
/dev/mmcblk0p2 on / type ext4 (rw,relatime,data=ordered)
[..]
/dev/mmcblk0p2 on /media/0d6d30bb-1671-4656-9f6e-a49e309f81af type ext4 (rw,relatime,data=ordered)

The last line is showing the issue. I have to umount to prevent a security breach.

**Comment by LemonBoy** [comment]
ldm tries to mount all the available partitions when started, you can mark your boot partition as noauto in the fstab to tell ldm you don't want it to mess with that

**Comment by pejobo** [comment]
Will do this. Thanks for the advice.

**Comment by pejobo** [comment]
Added a line in /etc/fstab but the partition is still showing up in the mount dir of ldm..?!

**Comment by LemonBoy** [comment]
I've tried this just now and it works as intended.
(the 'mask' branch has been merged into master a couple of days ago)

**Comment by pejobo** [comment]
I'm really sorry, it was a typo in my fstab. It's working as you said.
