### ISSUE TITLE
ldm: invalid option -- 'r'

### ISSUE THREAD

**Issue by benoliver999** [LemonBoy/ldm#45]
Running ldm with systemctl, I'm trying to umount a device with

    ldm -r /mnt/mydevice

And I get

    ldm: invalid option -- 'r'

This has never failed me in the past but recently it's been giving me the above error.

**Comment by LemonBoy** [comment]
Goodbye ldm -r, hello ldmc -r :)
For more informations there's always the good old (new) man page for ldmc [1]

[1] https://github.com/LemonBoy/ldm/blob/master/ldmc.pod

**Comment by benoliver999** [comment]
Ah - makes sense! I ran a quick `ldm -h` to see but I missed ldmc!
