### ISSUE TITLE
small readme fix

### ISSUE THREAD

**Issue by flatr0ze** [LemonBoy/ldm#47]
I believe

`USER_GID = gid USER_UID = uid BASE_MOUNTPOINT = /mnt`

should be

```
USER_GID = gid
USER_UID = uid
BASE_MOUNTPOINT = /mnt
```

thank you for the tool

**Comment by LemonBoy** [comment]
Hello,
I'd happily accept a PR fixing this :)

**Comment by flatr0ze** [comment]
Oh, c'mon man, it's just one line Ü
