### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by pejobo** [LemonBoy/ldm#48]
I experimented with the option and got a core dump when specifying a script as "-c".
Version is 0.6 (from arch aur). Architecture is armv7 (raspberry pi).
My use case is an automated backup of my photos as soon as the camera sd card is mounted.

The service is then dead and won't restart, because the /run/ldm.pid file still exists after a crash.
I helped me by adding a "ExecStartPre" call in the systemd unit file which deletes the file. Perhaps specifying the option "PIDFile" would work too. Don't know if systemd will clean up the file in case of crashes.

My ExecStartPre script now looks like this:
```bashb
#!/usr/bin/bash
# Used as ExecStartPre in systemd unit file for ldm v0.6
# 1)
#    removes pid file after crash, ldm won't start if the file exists
# 2)
#    try to delete orphaned mount points (e.g. after crash or power off)
#    ldm does no clean up / check itself
if [ -b /run/ldm.pid ] ; then
    echo "remove pid file after crash"
    rm /run/ldm.pid
fi
dir=$1
if [ "$dir" = "" ]; then
    echo mount point not specified, assuming default..
    dir=/mnt
fi
echo cleaning up mount directory "$dir"
for f in "$dir/*/"; do
    rmdir --ignore-fail-on-non-empty $f
done
exit 0
```

Output of journalctl --unit=ldm
```
Jul 04 00:22:09 pi2 ldm[12147]: strtoul: Success
Jul 04 00:22:09 pi2 ldm[12147]: ldm v0.6
... [stop and restart with -c option]
Jul 04 00:22:10 pi2 ntfs-3g[12154]: Unmounting /dev/sdb1 (Intenso)
Jul 04 00:22:55 pi2 systemd[1]: ldm.service: Main process exited, code=dumped, status=11/SEGV
Jul 04 00:22:55 pi2 systemd[1]: ldm.service: Unit entered failed state.
Jul 04 00:22:55 pi2 systemd[1]: ldm.service: Failed with result 'core-dump'.
Jul 04 00:22:59 pi2 systemd-coredump[12184]: Process 12147 (ldm) of user 0 dumped core.
Jul 04 00:24:20 pi2 systemd[1]: Started lightweight device mounter.
Jul 04 00:24:20 pi2 systemd[1]: Starting lightweight device mounter...
Jul 04 00:24:20 pi2 ldm[12214]: strtoul: Success
Jul 04 00:24:20 pi2 ldm[12214]: ldm is already running!
```

**Comment by pejobo** [comment]
I also got an core-dump without -c option when i plugged in a vfat formatted sd card.. :(

**Comment by LemonBoy** [comment]
It should be ok now :)

**Comment by pejobo** [comment]
No update yet for the arch AUR repositoy?

**Comment by LemonBoy** [comment]
Oh I was expecting a reply from you before bumping the version and update the PKGBUILD

**Comment by pejobo** [comment]
Ok, sorry. I just returned from vacation and am in the usual update loop..
I'm currently running "ldm 0.6.1-2" without the "-c" option and still get a core dump.
But I checked the build date, it's from 4th of july (oh, how much I hate this "x days ago" on github), so it seems too old to say if your fix works. 
I'll check tomorrow with a clean build. It's all in master now? Package ldm-git is also too old, so I'll have to build manually again?

**Comment by LemonBoy** [comment]
Well the commit landed on the 7th of July heh
The ldm-git package should just fetch the latest version so it should be fine

**Comment by pejobo** [comment]
With ldm-git I could not reproduce the crash. So the fix seems to work, well done ;)

**Comment by pejobo** [comment]
One observation with ldm-git: When unmounting (with umount) the mount directory is not removed, log:
```
Jul 25 22:51:36 pi2 systemd[1]: Started lightweight device mounter.
Jul 25 22:51:36 pi2 ldm[27919]: ldm v0.6.1-3-gba82260
Jul 25 22:51:36 pi2 ldm[27919]: strtoul: Success
Jul 25 22:51:36 pi2 ldm[27919]: Entering the main loop
Jul 25 23:04:23 pi2 ldm[27919]: FUSE exfat 1.1.0
Jul 25 23:04:23 pi2 ldm[27919]: WARN: volume was not unmounted cleanly.
Jul 25 23:04:23 pi2 mount.exfat[28204]: volume was not unmounted cleanly
Jul 25 23:20:54 pi2 ldm[27919]: Could not mkdir() the folder at /media/USB-4GB (File exists)
```

**Comment by LemonBoy** [comment]
Argh, don't use umount, there's ldmc -r for that!

**Comment by pejobo** [comment]
Yes, ldmc -r is working. I had the impression "umount" was working in earlier versions?! That's what kodi is calling from context menu..

**Comment by LemonBoy** [comment]
When using umount (or everything else that's not ldmc) the daemon can only see the device isn't mounted anymore (this is done by monitoring the fstab) hence it just unregisters it from the list of the devices it handles. 
I've now fixed the problem that made ldm fail when the previous directory wasn't removed so it should be fine either way :)
