### ISSUE TITLE
Error while mounting /dev/sr0 (Read-only file system)

### ISSUE THREAD

**Issue by Stephen304** [LemonBoy/ldm#50]
I am trying to use ldm to auto mount CDs inserted into my HTPC. Since CDs are read only, ldm fails to mount it. It would be nice if I could specify to mount everything read only or maybe even have ldm mount as read only when the above error is encountered.

Thoughts?

**Comment by Stephen304** [comment]
I made a PR with a fix for this - it just adds the read only flag for CDs and DVDs so they can successfully mount. Tested to work when booting with a DVD already in and with inserting / removing discs after boot.

**Comment by LemonBoy** [comment]
Fixed :) Thanks for reporting the issue and providing a patch!
