### ISSUE TITLE
ldm mounts old burned dd iso.

### ISSUE THREAD

**Issue by masterkorp** [LemonBoy/ldm#55]
I recently dd'ed a debian iso onto a device. 

After that I deleted all the partitions with fdisk, created a new DOS partition table and a new partition.

I did format the partition with ``mkfs.vfat /dev/sdb1`` and the usb drive does mount correctly with ``mount /dev/sdb1 /mnt``. but with ldm, its mount like this.
```
/dev/sdb on /media/Debian_8.2.0_M-A_1 type iso9660 (ro,relatime,uid=1000,gid=1000,utf8)
```

And the files of the iso are still listed.

On a Gnome 3 DE with all the features, the device does mount fine.

Here is a fdisk -l of the device.

```
Disk /dev/sdb: 14.6 GiB, 15610576896 bytes, 30489408 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xb72e99e2

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1        2048 30489407 30487360 14.6G 83 Linux
```

Any suggestions would be welcome.

Regards,

**Comment by LemonBoy** [comment]
This is..weird. Did you try re-doing the partitioning too ?

**Comment by masterkorp** [comment]
Hello, sorry for the delay.
Yes I did the partitioning too.

**Comment by LemonBoy** [comment]
As you can see `/dev/sdb` is mounted, which is the whole disk and not a single partition. The hybrid ISOs you dd'd to the device is still there. You might want to try erasing some blocks at the beginning, then re-do the partitioning and mkfs it afterwards.
