### ISSUE TITLE
ldm v0.6.2 doesn't automount cdrtools data DVD-RW

### ISSUE THREAD

**Issue by jmcamp** [LemonBoy/ldm#57]
I'm using Arch Linux with cdrtools v3.02a03-1 and ldm v0.6.2.  I burned data onto a blanked DVD-RW using:

tsize=`mkisofs -J -r -N -d -hide-rr-moved -udf -print-size "$source"`
mkisofs -J -r -N -d -hide-rr-moved -udf -V "$label" "$source" | cdrecord -v -eject gracetime=3 dev=$device driveropts=burnfree tsize=$tsize\s -data -pad -

This DVD-RW is not automounted by ldm v0.6.2.  It does automount ok if I downgrade ldm to v0.5 or if I manually mount it using "mount /dev/sr0 /mnt".

Other DVD-RWs I created using Windows are automounted by ldm v0.6.2, it's just the one I created using cdrtools that doesn't work.

I run ldm by:  ldm -d -g 100 -u 1000 -p /media.

**Comment by LemonBoy** [comment]
What does `udevadm info /dev/sr0` return when the DVD is inserted ?

**Comment by jmcamp** [comment]
P: /devices/pci0000:00/0000:00:11.0/ata4/host3/target3:0:0/3:0:0:0/block/sr0
N: sr0
L: -100
S: cdrom
S: disk/by-id/ata-ATAPI_iHAS124_W_3524602_278332505268
S: disk/by-label/ldm_test
S: disk/by-path/pci-0000:00:11.0-ata-4
S: disk/by-uuid/2015-12-10-01-49-56-33
E: DEVLINKS=/dev/disk/by-label/ldm_test /dev/disk/by-uuid/2015-12-10-01-49-56-33 /dev/cdrom /dev/disk/by-id/ata-ATAPI_iHAS124_W_3524602_278332505268 /dev/disk/by-path/pci-0000:00:11.0-ata-4
E: DEVNAME=/dev/sr0
E: DEVPATH=/devices/pci0000:00/0000:00:11.0/ata4/host3/target3:0:0/3:0:0:0/block/sr0
E: DEVTYPE=disk
E: ID_ATA=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_BUS=ata
E: ID_CDROM=1
E: ID_CDROM_CD=1
E: ID_CDROM_CD_R=1
E: ID_CDROM_CD_RW=1
E: ID_CDROM_DVD=1
E: ID_CDROM_DVD_PLUS_R=1
E: ID_CDROM_DVD_PLUS_RW=1
E: ID_CDROM_DVD_PLUS_R_DL=1
E: ID_CDROM_DVD_R=1
E: ID_CDROM_DVD_RAM=1
E: ID_CDROM_DVD_RW=1
E: ID_CDROM_MEDIA=1
E: ID_CDROM_MEDIA_DVD_PLUS_RW=1
E: ID_CDROM_MEDIA_SESSION_COUNT=1
E: ID_CDROM_MEDIA_STATE=complete
E: ID_CDROM_MEDIA_TRACK_COUNT=1
E: ID_CDROM_MEDIA_TRACK_COUNT_DATA=1
E: ID_CDROM_MRW=1
E: ID_CDROM_MRW_W=1
E: ID_FS_APPLICATION_ID=MKISOFS\x20ISO9660\x2fHFS\x2fUDF\x20FILESYSTEM\x20BUILDER\x20\x26\x20CDRECORD\x20CD\x2fDVD\x2fBluRay\x20CREATOR\x20\x28C\x29\x201993\x20E.YOUNGDALE\x20\x28C\x29\x201997\x20J.PEARSON\x2fJ.SCHILLING
E: ID_FS_LABEL=ldm_test
E: ID_FS_LABEL_ENC=ldm_test
E: ID_FS_SYSTEM_ID=LINUX
E: ID_FS_TYPE=udf
E: ID_FS_USAGE=filesystem
E: ID_FS_UUID=2015-12-10-01-49-56-33
E: ID_FS_UUID_ENC=2015-12-10-01-49-56-33
E: ID_FS_VERSION=Joliet Extension
E: ID_MODEL=ATAPI_iHAS124_W
E: ID_MODEL_ENC=ATAPI\x20\x20\x20iHAS124\x20\x20\x20W\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_PATH=pci-0000:00:11.0-ata-4
E: ID_PATH_TAG=pci-0000_00_11_0-ata-4
E: ID_REVISION=HL0E
E: ID_SERIAL=ATAPI_iHAS124_W_3524602_278332505268
E: ID_SERIAL_SHORT=3524602_278332505268
E: ID_TYPE=cd
E: MAJOR=11
E: MINOR=0
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=1916929

**Comment by LemonBoy** [comment]
From a quick glance I can't see anything wrong with this.
Is there anything interesting in `journalctl` ?

**Comment by jmcamp** [comment]
Ahh, there's a "permission denied" error in journalctl.

My guess is this error was fixed by this commit:
https://github.com/LemonBoy/ldm/commit/ab3823eb4febe97b30e602b0ae9f32c06589bb8e

This commit hasn't been included in a ldm release yet, so I don't currently have the fix.  I'll try compiling ldm from latest git ...

**Comment by jmcamp** [comment]
Works with git code!  So the bug fixed by https://github.com/LemonBoy/ldm/commit/ab3823eb4febe97b30e602b0ae9f32c06589bb8e was the reason why ldm v0.6.2 was not automounting my DVD with a UDF filesystem.
