### ISSUE TITLE
Error starting ldm.service

### ISSUE THREAD

**Issue by dummys** [LemonBoy/ldm#58]
Hi,

Latest AUR package from arch linux. Good mountpoint/mount_owner in ldm.conf.

When starting with systemctl start ldm.service
ldm realpath(): No such file or directory

When starting with /usr/bin/ldm -u USER -p mountpoint, working sucessfully.
An idea ?
thanks

**Comment by tjaartvdwalt** [comment]
Why do you close an issue without stating what the resolution is? I have a similar issue, but this is of no help at all to resolve it.
