### ISSUE TITLE
Cannot unmount properly with ldm -r exfat

### ISSUE THREAD

**Issue by dummys** [LemonBoy/ldm#60]
Hello,

After issuing ldmc -r /mnt/xxx:

jan 10 11:40:06 MacBookPwn kernel: sd 11:0:0:0: [sdd] Write Protect is off
jan 10 11:40:06 MacBookPwn kernel: sd 11:0:0:0: [sdd] Mode Sense: 23 00 00 00
jan 10 11:40:06 MacBookPwn kernel: sd 11:0:0:0: [sdd] Write cache: disabled, read cache: disabled, doesn't support DPO or FUA
jan 10 11:40:06 MacBookPwn kernel:  sdd: sdd1
jan 10 11:40:06 MacBookPwn kernel: sd 11:0:0:0: [sdd] Attached SCSI removable disk
jan 10 11:40:06 MacBookPwn systemd[1]: Mounted /mnt/351B-3566.
jan 10 11:40:33 MacBookPwn systemd[1]: mnt-351B\x2d3566.mount: Unit entered failed state.

And after removing / puting back, the fs need to be repared.

**Comment by LemonBoy** [comment]
Interesting. Is there anything interesting in dmesg/journalctl ? The failed mount unit worries me, journalctl status might shed some light.

**Comment by dummys** [comment]
No,  there is only this in journalctl - fl

**Comment by dummys** [comment]
What else did you need for debug?

**Comment by LemonBoy** [comment]
`systemctl status mnt-351B\x2d3566.mount` should show what happened to the unit.

**Comment by dummys** [comment]
look this:

$ ldmc -r /mnt/D595-9745
Operation completed successfully
ldmc -l               
v "/dev/sdc1" "exfat" "/mnt/D595-9745"

Then fsck:
sudo fsck /dev/sdc1
fsck from util-linux 2.27.1
exfatfsck 1.2.0
WARN: volume was not unmounted cleanly.
Checking file system on /dev/sdc1.
File system version           1.0
Sector size                 512 bytes
Cluster size                 32 KB
Volume size                7448 MB
Used space                 1216 KB
Available space            7447 MB
Totally 1 directories and 1 files.

Then plugin back:

/dev/sdc1 on /mnt/D595-9745 type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096)


Jan 11 12:22:18 mofobox kernel:  sdc: sdc1
Jan 11 12:22:18 mofobox kernel: sd 35:0:0:0: [sdc] Attached SCSI removable disk
Jan 11 12:22:18 mofobox ldm[3532]: FUSE exfat 1.2.0
Jan 11 12:22:18 mofobox ldm[3532]: WARN: volume was not unmounted cleanly.
Jan 11 12:22:18 mofobox mount.exfat[6143]: volume was not unmounted cleanly

Then the units:

Jan 11 12:23:48 mofobox systemd[1]: dev-sdc1.device: Job dev-sdc1.device/start timed out.
Jan 11 12:23:48 mofobox systemd[1]: Timed out waiting for device USB_DISK 1.
Jan 11 12:23:48 mofobox systemd[1]: dev-sdc1.device: Job dev-sdc1.device/start failed with result 'timeout'.

-> $ sudo systemctl status -l dev-sdc1.device                                                       3 ↵
● dev-sdc1.device - USB_DISK 1
   Loaded: loaded
   Active: activating (tentative) since Mon 2016-01-11 12:22:18 CET; 2min 3s ago
   Device: /sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.4/1-1.4:1.0/host34/target34:0:0/34:0:0:0/block/sdc/sdc1

Jan 11 12:23:48 mofobox systemd[1]: dev-sdc1.device: Job dev-sdc1.device/start timed out.
Jan 11 12:23:48 mofobox systemd[1]: Timed out waiting for device USB_DISK 1.
Jan 11 12:23:48 mofobox systemd[1]: dev-sdc1.device: Job dev-sdc1.device/start failed with result 'timeout'.

when ldmc -r:

Jan 11 12:24:49 mofobox systemd[1]: mnt-D595\x2d9745.mount: Unit entered failed state.

-> $ sudo systemctl status -l dev-sdc1.device       
● dev-sdc1.device - USB_DISK 1
   Loaded: loaded
   Active: activating (tentative) since Mon 2016-01-11 12:24:49 CET; 14s ago
   Device: /sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.4/1-1.4:1.0/host34/target34:0:0/34:0:0:0/block/sdc/sdc1

then removing physically the device:

Jan 11 12:25:26 mofobox kernel: usb 1-1.4: USB disconnect, device number 78
Jan 11 12:25:26 mofobox systemd[1]: mnt-D595\x2d9745.mount: Unit entered failed state.
Jan 11 12:25:26 mofobox mount.exfat[7216]: failed to write super block

**Comment by dummys** [comment]
no news ?

**Comment by LemonBoy** [comment]
You still didn't provide the status for the `.mount` unit. Also, does this work with other methods ? (eg, mount/umount or udisks or whatever)

**Comment by dummys** [comment]
Yes it works with other method.

Here is the .mount:

(mofo@mofobox) [~] [12:39:00] [git:master ✘]
-> $ sudo systemctl status -l  mnt-A261\x2d72B6.mount
● mnt-A261x2d72B6.mount
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Jan 14 12:37:13 mofobox kernel:  sdd: sdd1
Jan 14 12:37:13 mofobox kernel: sd 7:0:0:0: [sdd] Attached SCSI removable disk
Jan 14 12:37:33 mofobox kernel: usb 1-1.4: USB disconnect, device number 31
Jan 14 12:37:33 mofobox systemd[1]: Unmounting /mnt/A261-72B6...
Jan 14 12:37:33 mofobox kernel: FAT-fs (sdd1): FAT read failed (blocknr 3038)
Jan 14 12:37:33 mofobox kernel: FAT-fs (sdd1): unable to read boot sector to mark fs as dirty
Jan 14 12:37:33 mofobox systemd[1]: Unmounted /mnt/A261-72B6.
Jan 14 12:37:54 mofobox kernel: usb 1-1.4: new high-speed USB device number 32 using ehci-pci
Jan 14 12:37:54 mofobox kernel: usb-storage 1-1.4:1.0: USB Mass Storage device detected
Jan 14 12:37:54 mofobox kernel: scsi host8: usb-storage 1-1.4:1.0
Jan 14 12:37:55 mofobox kernel: scsi 8:0:0:0: Direct-Access                               1.00 PQ: 0 ANSI: 6
Jan 14 12:37:55 mofobox kernel: sd 8:0:0:0: [sdd] 15257600 512-byte logical blocks: (7.81 GB/7.27 GiB)
Jan 14 12:37:55 mofobox kernel: sd 8:0:0:0: [sdd] Write Protect is off
Jan 14 12:37:55 mofobox kernel: sd 8:0:0:0: [sdd] Mode Sense: 23 00 00 00
Jan 14 12:37:55 mofobox kernel: sd 8:0:0:0: [sdd] Write cache: disabled, read cache: disabled, doesn't support DPO or FUA
Jan 14 12:37:55 mofobox kernel:  sdd: sdd1
Jan 14 12:37:55 mofobox kernel: sd 8:0:0:0: [sdd] Attached SCSI removable disk
Jan 14 12:37:55 mofobox kernel: FAT-fs (sdd1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.


After ldmc -r 

Jan 14 12:39:07 mofobox kernel: usb 1-1.4: USB disconnect, device number 32
Jan 14 12:39:07 mofobox systemd[1]: Unmounting /mnt/A261-72B6...
Jan 14 12:39:07 mofobox umount[20147]: umount: /mnt/A261-72B6: not mounted
Jan 14 12:39:07 mofobox systemd[1]: mnt-A261\x2d72B6.mount: Mount process exited, code=exited status=32
Jan 14 12:39:07 mofobox systemd[1]: Unmounted /mnt/A261-72B6.
Jan 14 12:39:07 mofobox systemd[1]: mnt-A261\x2d72B6.mount: Unit entered failed state.
Jan 14 12:39:07 mofobox kernel: FAT-fs (sdd1): unable to read boot sector to mark fs as dirty
Jan 14 12:39:22 mofobox sudo[20249]:     mofo : TTY=pts/6 ; PWD=/home/mofo ; USER=root ; COMMAND=/usr/bin/systemctl status -l mnt-A261x2d72B6.mount

**Comment by LemonBoy** [comment]
This is extremely weird, systemd is trying to unmount the device after something (ldm ?) has already unmounted it (?).
And why the hell there's a usb-disconnect notification there ?
Please make sure there are no other tools that provide the same service running, your computer might be haunted by satan itself.

**Comment by dummys** [comment]
the usb disconnect is only here because I pulled out the device after ldmc -r ...

It's a fresh up2date Arch linux without any weird package. Only yours...

**Comment by LemonBoy** [comment]
I've just tried to reproduce this bug by formatting a sdhc using `mkfs.exfat` and then plugging it into the card reader. I was able to shuffle the files around and was also able to remove it successfully with `ldmc -r`...

**Comment by dummys** [comment]
Weird, did you see womething wrong in my systemd ? The computer is a dell 7010.
Perhaps it's only because it's a usb key ? Can you try it with usb key ?

**Comment by LemonBoy** [comment]
*shrug* at the moment I can't really do further testing but after a quick glance it seems you have a udisks.service there.

**Comment by dummys** [comment]
-> $ sudo systemctl status -l udisks2.service     
● udisks2.service - Disk Manager
   Loaded: loaded (/usr/lib/systemd/system/udisks2.service; static; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:udisks(8)

**Comment by dummys** [comment]
OMFG you are right:

extra/udisks2 2.1.6-1 [installed]
    Disk Management Service, version 2

**Comment by dummys** [comment]
Ok now:

Jan 14 16:20:28 mofobox kernel: usb 1-1.4: new high-speed USB device number 49 using ehci-pci
Jan 14 16:20:28 mofobox kernel: usb-storage 1-1.4:1.0: USB Mass Storage device detected
Jan 14 16:20:28 mofobox kernel: scsi host11: usb-storage 1-1.4:1.0
Jan 14 16:20:29 mofobox kernel: scsi 11:0:0:0: Direct-Access                               1.00 PQ: 0 ANSI: 6
Jan 14 16:20:29 mofobox kernel: sd 11:0:0:0: [sdc] 15257600 512-byte logical blocks: (7.81 GB/7.27 GiB)
Jan 14 16:20:29 mofobox kernel: sd 11:0:0:0: [sdc] Write Protect is off
Jan 14 16:20:29 mofobox kernel: sd 11:0:0:0: [sdc] Mode Sense: 23 00 00 00
Jan 14 16:20:29 mofobox kernel: sd 11:0:0:0: [sdc] Write cache: disabled, read cache: disabled, doesn't support DPO or FUA
Jan 14 16:20:29 mofobox kernel:  sdc: sdc1
Jan 14 16:20:29 mofobox kernel: sd 11:0:0:0: [sdc] Attached SCSI removable disk
Jan 14 16:20:49 mofobox systemd[1]: mnt-A261\x2d72B6.mount: Unit entered failed state.

But the device is unmounted now.

But I don't know why there is still this pesky unit... No more udisk2

-> $ yaourt -Ss udisks 
extra/udisks 1.0.5-2
    Disk Management Service
extra/udisks2 2.1.6-1
    Disk Management Service, version 2

**Comment by LemonBoy** [comment]
The `mount-` unit must be there and if ldm is running it should've mounted the device.
Does that happen right after plugging the key in ? If so I guess the mount command failed and there should be some error message for you to read in `journalctl -xe`.

**Comment by dummys** [comment]
so now I rebooted.

Then : stopping ldm.service, plug the key, nothing in log, unplugging the key, nothing in log.

Starting ldm.service, putting the key: nothing in log, mount show the key. ldmc -l show the key. ldmc -r /mnt/key, ldmc -l nothing, but mount still show the key. unplugging the key shows:

Jan 14 16:46:06 mofobox kernel: usb 1-1.4: USB disconnect, device number 8
Jan 14 16:46:06 mofobox systemd[1]: Unmounting /mnt/A261-72B6...
Jan 14 16:46:06 mofobox kernel: FAT-fs (sdc1): FAT read failed (blocknr 3038)
Jan 14 16:46:06 mofobox kernel: FAT-fs (sdc1): unable to read boot sector to mark fs as dirty
Jan 14 16:46:06 mofobox systemd[1]: Unmounted /mnt/A261-72B6.

**Comment by dummys** [comment]
-> $ sudo systemctl status -l mnt-A261\\x2d72B6.mount                                               3 ↵
● mnt-A261\x2d72B6.mount
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Jan 14 16:46:06 mofobox systemd[1]: Unmounting /mnt/A261-72B6...
Jan 14 16:46:06 mofobox systemd[1]: Unmounted /mnt/A261-72B6.

**Comment by dummys** [comment]
Do i need "sudo ldmc -r" or "ldmc -r" ?

**Comment by LemonBoy** [comment]
Follow those steps:
1) Put the system in a clean state.
2) Make sure ldm.service is started.
3) Plug the key in.
4) Make sure the volume has been mounted.
5) Use `ldmc -r` (w/o sudo).
6) At this point gather the output of `mount`, `journalctl -xn`, `dmesg | tail`, `lsblk` and for the love of whatever you believe in put those in a pastebin. Do not plug the usb key without unmounting the filesystem, that's what corrupts the FS.
7) Since the key is still mounted, do a clean unmount using the `umount` utility, then unplug the key.
8) Report back the information requested in the form of a pastebin link.
9) Thanks for flying with us.

**Comment by dummys** [comment]
ok will do it tomorrow

**Comment by LemonBoy** [comment]
The latest couple of commits should help, can you test ?

**Comment by dummys** [comment]
It's ok. Thanks for fix.
