### ISSUE TITLE
Feature request: notifications

### ISSUE THREAD

**Issue by famfop** [LemonBoy/ldm#61]
Hi,
I'm sorry to write it to the 'Issues'-place but I couldn't find a more appropriate place. Would it be possible (maybe as a patch or so) to implement notifications, e.g. when a disk gets mounted? I'd love it!

**Comment by LemonBoy** [comment]
By pairing the `-c` switch with a custom script that uses `notify-send` (don't forget to set the DISPLAY variable) should do the trick.
