### ISSUE TITLE
Mount point replaces spaces with underscores.

### ISSUE THREAD

**Issue by Tmplt** [LemonBoy/ldm#62]
A file system with the label `Windows - Primary` will be mounted at `$BASE_MOUNTPOINT/Windows_-_Primary/` instead of `$BASE_MOUNTPOINT/Windows - Primary/`.

**Comment by LemonBoy** [comment]
This is a feature :)

**Comment by Tmplt** [comment]
I fail to see the advantage of this. Could you explain why it is a feature (unless the feature is a bug, and vice-versa, and I'm missing the joke)?

**Comment by LemonBoy** [comment]
It's a leftover from the time when ldm used `system()` instead of `libmount`, it also helps to avoid quoting the whole name every time or adding a bunch of backslashes.

**Comment by Tmplt** [comment]
Ah yes, that makes sense.

Thanks!
