### ISSUE TITLE
using systemd ldm.service

### ISSUE THREAD

**Issue by tjaartvdwalt** [LemonBoy/ldm#64]
Hi thanks for a very nice project,
 
I believe my issue is similar to #58, but that issue was closed without documention the solution.

The problem occurs when I try to start ldm as a systemd service. When I start it manually it works fine. From the output below it seems the value of the `${MOUNT_OWNER}` is empty.

> May 23 11:24:04 tjaart-laptop systemd[1]: Started lightweight device mounter.
> May 23 11:24:04 tjaart-laptop ldm[5138]: Could not find any information about the user ""
> May 23 11:24:04 tjaart-laptop systemd[1]: ldm.service: Main process exited, code=exited, status=1/FAILURE
> May 23 11:24:04 tjaart-laptop systemd[1]: ldm.service: Unit entered failed state.
> May 23 11:24:04 tjaart-laptop systemd[1]: ldm.service: Failed with result 'exit-code

I am not sure how this needs to be configured. Does anyone have any pointers?

**Comment by LemonBoy** [comment]
The `INSTALL` section of the readme explicitly mentions that `MOUNT_OWNER` and `BASE_MOUNTPOINT` are taken from the `/etc/ldm.conf` file, do you have one ?

**Comment by tjaartvdwalt** [comment]
Ah ok, I think my `ldm.conf` is outdated... the old file, which does not seem to work contains:

```
USER_GID=1000
USER_UID=1000
BASE_MOUNTPOINT = /mnt
```

If I change it to the following, it works:
```
MOUNT_OWNER=MY_USERNAME
BASE_MOUNTPOINT=/mnt

```
