### ISSUE TITLE
Use -c option when using the systemd service

### ISSUE THREAD

**Issue by tkarls** [LemonBoy/ldm#67]
Using the systemd service file as it is makes it impossible to specify a callback script since only two parameters are supported in the settings file.

I think a good way to support everything would be to add a environment variable "ADDITIONAL_ARGS" 

So one could set
````
ADDITIONAL_ARGS="-c /path/to/my/script"
````

in the settings file and the systemd service file should look like:
````
ExecStart=/usr/bin/ldm -u ${MOUNT_OWNER} -p ${BASE_MOUNTPOINT} ${ADDITIONAL_ARGS}
````

**Comment by LemonBoy** [comment]
The service file covers the basic needs of the average user, an advanced user who needs to set their own `-c` scripts or to set the {f,u}mask could just use that as a starting point, I feel that a free-form variable for additional parameters is just asking for trouble heh
Feel free to re-open this ticket if you have any more questions!
