### ISSUE TITLE
AUT ldm package does not install systemd

### ISSUE THREAD

**Issue by alexkutsan** [LemonBoy/ldm#68]
Packagebuild from aur https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ldm does not install systemd service.
As I can see from https://github.com/LemonBoy/ldm/blob/master/Makefile installing systemd service processed only with command
`make install systemd`
But PKGBUILD does only install
So additional string should be added to PKGBUILD:

```
    make PREFIX=/usr DESTDIR="$pkgdir" install
    make PREFIX=/usr DESTDIR="$pkgdir" install systemd
```

 @LemonBoy looks like you is mainteiner of https://aur.archlinux.org/packages/ldm/?comments=all

**Comment by LemonBoy** [comment]
Not really, the `install` target also calls the `install-systemd` one
