### ISSUE TITLE
ldm.service loaded but failed

### ISSUE THREAD

**Issue by meriops** [LemonBoy/ldm#69]
Hi

Immediately after installation of ldm, when I plug in a USB memory, the name of the device quickly flashes in thunar (archlinux, i3) and disappear. After reboot, nothing happens and systemd logs that the ldm.service is loaded but failed. Then, `systemctl status ldm.service` indicates that `realpath()`does not exist... I am not sure whether it is a problem on my system or with ldm... Any clue?
Thanks

**Comment by LemonBoy** [comment]
Can you please post the error message verbatim along with your `ldm.conf` ?

**Comment by meriops** [comment]
My ldm.conf contains only the following: 
```
MOUNT_OWNER=ol                                                                                                                  BASE_MOUNTPOINT=/run/media/
```

And here is the output from `systemctl status ldm`:

```
● ldm.service - lightweight device mounter
   Loaded: loaded (/usr/lib/systemd/system/ldm.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-09-29 19:17:05 CEST; 4min 42s ago
  Process: 375 ExecStart=/usr/bin/ldm -u ${MOUNT_OWNER} -p ${BASE_MOUNTPOINT} (code=exited, status=1/FAILURE)
 Main PID: 375 (code=exited, status=1/FAILURE)

Sep 29 19:17:05 archoli systemd[1]: Started lightweight device mounter.
Sep 29 19:17:05 archoli ldm[375]: realpath(): No such file or directory
Sep 29 19:17:05 archoli systemd[1]: ldm.service: Main process exited, code=exited, status=1/FAILURE
Sep 29 19:17:05 archoli systemd[1]: ldm.service: Unit entered failed state.
Sep 29 19:17:05 archoli systemd[1]: ldm.service: Failed with result 'exit-code'.
zsh: exit 3     systemctl status ldm
```

**Comment by LemonBoy** [comment]
Thanks for the detailed report, in the latest commit I've added some code to give a more informative error message in similar cases.
What the error message really meant is that the `/run/media/` folder doesn't exist on your system and since ldm doesn't create it when it is not present it just exits out.
