### ISSUE TITLE
EXTRA_ARGS example

### ISSUE THREAD

**Issue by kaihendry** [LemonBoy/ldm#76]
Sorry, I created an issue when I was trying to search.

What I am trying to achieve is:

1. Plug in SDCARD
2. Automounts via `/dev/mmcblk0p1 /mnt/sdcard/ exfat defaults,nofail 0 0`
3. $HOME/stared.sh is executed as uid=1000 & gid=1000

If I can achieve this with ldm, please let me know.

**Comment by LemonBoy** [comment]
> Sorry, I created an issue when I was trying to search.

No problem.

You just have to modify the conf file (`/etc/ldm.conf` if you're using the default systemd unit) and add a line like `EXTRA_ARGS=-c /home/yourusername/started.sh`.

**Comment by kaihendry** [comment]
```
hendry@knuckles ~ $ sudo ldmc -l                                                                                                                          [7/7]
hendry@knuckles ~ $ mount | grep sdcard
hendry@knuckles ~ $ cat /etc/sv/ldm/conf
MOUNT_OWNER=hendry
BASE_MOUNTPOINT=/mnt/sdcard
EXTRA_ARGS=-c /home/hendry/stared.sh
hendry@knuckles ~ $ head /home/hendry/stared.sh
#!/bin/bash -x
input=/mnt/sdcard/
date >> /tmp/stared-run.log
find $input -iname "*.jpg" | while read fn
do
if test $(exiv2 -Pv -g Xmp.xmp.Rating $fn) == 3
then
        dt=$(exiv2 -g Exif.Image.DateTime -Pv $fn)
        read -r date time <<< "$dt"
        IFS=: read -r year month day hour min secs <<< "$date"
hendry@knuckles ~ $ date
Tue Jun 23 19:11:01 +08 2020
hendry@knuckles ~ $ tail -f /tmp/stared-run.log
Tue Jun 23 15:06:46 +08 2020
Tue Jun 23 15:08:14 +08 2020
Tue Jun 23 15:08:15 +08 2020
Tue Jun 23 15:08:16 +08 2020
Tue Jun 23 15:08:17 +08 2020
Tue Jun 23 15:08:18 +08 2020
Tue Jun 23 15:16:30 +08 2020
Tue Jun 23 15:17:10 +08 2020
Tue Jun 23 15:19:39 +08 2020
Tue Jun 23 15:23:34 +08 2020

^C
```

I put in the sdcard here, it didn't run the script.

```
hendry@knuckles ~ $ sudo ldmc -l
v "/dev/mmcblk0p1" "exfat" "/mnt/sdcard/"
hendry@knuckles ~ $ mount | grep sdcard
/dev/mmcblk0p1 on /mnt/sdcard type exfat (rw,relatime,uid=99,gid=99,fmask=0000,dmask=0000,allow_utime=0022,iocharset=utf8,errors=remount-ro,uhelper=ldm)
hendry@knuckles ~ $ sudo ldmc -l
v "/dev/mmcblk0p1" "exfat" "/mnt/sdcard/"
(reverse-i-search)`-r': tail /tmp/stared^Cun.log
hendry@knuckles ~ $ sudo ldmc -r /mnt/sdcard/
The operation didn't complete successfully
```

What am I missing please?

**Comment by LemonBoy** [comment]
The use of `runit` suggests you're using Void Linux. The [service file](https://github.com/void-linux/void-packages/blob/master/srcpkgs/ldm/files/ldm/run) is slightly different than the systemd service: the conf file should be something like this:
```
OPTS=-u hendry -p /mnt/ -c /home/hendry/stared.sh
```

A few notes:
* `-p` (or `BASE_MOUNTPOINT`) refers to the root folder where `ldm` creates a sub-folder for each mounted device.
* `ldm` passes a few environment variables to let the script know what's going on (`LDM_ACTION`) and what the chosen mount point is (`LDM_MOUNTPOINT`), you don't need to hardcode any path.
* `ldmc` works without `sudo`, that's the only reason it exists. You can also unmount any `ldm`-managed device with `umount`

**Comment by kaihendry** [comment]
Thank you for your support! I found OPTS needed to to be quoted else it complained that "hendry" was a command in the substitution.

Can I assume that I need to manually unmount using `lmdc -r` when removing the sdcard?

```
hendry@knuckles ~ $ ldmc -l
v "/dev/mmcblk0p1" "exfat" "/mnt/sdcard/"
hendry@knuckles ~ $ ldmc -r /mnt/sdcard
The operation didn't complete successfully
hendry@knuckles ~ $ ldmc -l
v "/dev/mmcblk0p1" "exfat" "/mnt/sdcard/"
hendry@knuckles ~ $ ldmc -r /mnt/
The operation didn't complete successfully
hendry@knuckles ~ $ ldmc -l
v "/dev/mmcblk0p1" "exfat" "/mnt/sdcard/"
hendry@knuckles ~ $ ps aux | grep ldm
root      6222  0.0  0.0    908     4 ?        Ss   Jun23   0:00 runsv ldm
root     31789  0.0  0.0   3488  2156 ?        S    10:36   0:00 ldm -u hendry -p /mnt/ -c /home/hendry/stared.sh
hendry   32632  0.0  0.0   1708   512 pts/2    S+   10:45   0:00 grep --exclude-dir=node_modules --color=auto ldm
hendry@knuckles ~ $ mount | grep sdcard
/dev/mmcblk0p1 on /mnt/sdcard type exfat (rw,relatime,uid=1000,gid=1000,fmask=0000,dmask=0000,allow_utime=0022,iocharset=utf8,errors=remount-ro,uhelper=ldm)
hendry@knuckles ~ $
```

**Comment by LemonBoy** [comment]
> Can I assume that I need to manually unmount using lmdc -r when removing the sdcard?

Yes, `ldmc -r /mnt/sdcard` (or `umount /mnt/sdcard`) is enough to unmount the device.
If that fails it usually means the volume is still being used by some other process, `lsof` should be able to tell you which one.

**Comment by kaihendry** [comment]
Thank you, it appears to work. The final piece to the puzzle! https://youtu.be/2ZOIgFK1-YU
